CXX ?= c++
CFLAGS = -O2 -DLinux -DGCC -I$(EUSDIR)/include
LDFLAGS =
OBJOPT = -o
OUTOPT = -o
SOFLAGS = -shared
EXESFX =
LSFX = so
LPFX = lib

ifneq (,$(findstring 64,$(shell $(CXX) -dumpmachine)))
 CFLAGS+=-falign-functions=8
else
 CFLAGS+=-falign-functions=4
endif

ifneq ($(shell $(CXX) -dumpmachine | egrep "^(arm|aarch)"),)
  LDFLAGS+=-Wl,-z,execstack
  CFLAGS+=-DARM -fPIC
endif
ifneq ($(shell $(CXX) -dumpmachine | grep "^x86_64"),)
  CFLAGS+=-fPIC
endif

ifneq ($(shell $(CXX) -dumpmachine | grep "i.*86-linux"),)
CXX += -m32
endif


