CXX ?= c++
CFLAGS = -O2 -falign-functions=4 -DCygwin -I$(EUSDIR)/include
LDFLAGS =
OBJOPT = -o
OUTOPT = -o
SOFLAGS = -shared -falign-functions=4
EXESFX = .exe
LSFX = dll
LPFX = lib
LIBS = -L$(ARCHDIR) -lRAPID
