CC = c++
CFLAGS = -O2 -falign-functions=8 -fPIC -DDarwin -DGCC -I$(EUSDIR)/include
LDFLAGS =
OBJOPT = -o
OUTOPT = -o
LD = c++
SOFLAGS = -dynamiclib -flat_namespace -undefined suppress
EXELD = c++
EXESFX =
LSFX = so
LPFX = lib
LIBS = -L$(ARCHDIR) -lRAPID
