static pointer CLO62636();
static pointer CLO62645();
static pointer (*ftab[10])();

#define QUOTE_STRINGS_SIZE 155
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "system::find-entry",
    ":integer",
    "system::sysmod",
    "\"no such foreign entry ~s\"",
    "foreign-code",
    ":init",
    ":entry",
    "\"\"",
    "load",
    "setf",
    "symbol-function",
    "quote",
    "make-foreign-code",
    "dolist",
    "fname",
    "intern",
    "string-upcase",
    "nil",
    ":element-type",
    ":char",
    ":initial-contents",
    "make-array",
    "*calleus*",
    ":start1",
    "replace",
    "lambda-closure",
    "(lambda)",
    "closure",
    "code",
    "keywordp",
    "progn",
    "unintern",
    "*package*",
    "send",
    "let",
    "symbol",
    "foreign-pod",
    "string",
    "function",
    "lambda",
    ":pod-address",
    "sizeof-types",
    ":slotlist",
    "\".\"",
    "\"keyword expected for cstruct type\"",
    "*",
    ":pointer",
    ":slot",
    "\"no such cstruct slot ~s\"",
    "\"index out of range\"",
    "\"no such cstruct slot\"",
    "\"index out of range\"",
    ":access",
    "cstruct",
    ":super",
    "\".\"",
    "\"-\"",
    "\"SET-\"",
    "defun",
    "s",
    "system:peek",
    "defsetf",
    "val",
    "system:poke",
    ":long",
    "(:char :byte)",
    "&optional",
    "i",
    "if",
    "+",
    ":byte",
    "subseq",
    "&rest",
    "car",
    ":end2",
    "length",
    "declare",
    "fixnum",
    "\"illegal type specifier\"",
    "defclass",
    ":metaclass",
    "cstructclass",
    "super",
    ":get",
    ":set",
    "symbol-name",
    "\"-\"",
    "\"SET-\"",
    "\"SET-\"",
    "defcstruct",
    "carray",
    "0",
    "0",
    "foreign-string",
    "\"LISP\"",
    "\"LISP\"",
    "\"no such package\"",
    "(load-foreign defforeign make-foreign-code defvoidforeigns defun-c-callable pod-address byte-size cstructclass cstruct defcstruct carray defcarray foreign-string make-foreign-string)",
    ":find",
    "load-module",
    "\"(self class symname)\"",
    "\"(self class ent &optional param (result :integer))\"",
    "\"(fentry &optional param (result :integer) (fmod (system::sysmod)))\"",
    "load-foreign",
    "\"(file)\"",
    "defforeign",
    "\"(name fmod label param result)\"",
    "defvoidforeigns",
    "\"(mod &rest names)\"",
    "byte-string",
    "\"(&rest bytes)\"",
    "\"(self class)\"",
    "\"(self class param result func)\"",
    "defun-c-callable",
    "\"(name param &rest forms)\"",
    "pod-address",
    "\"(x)\"",
    ":vtype",
    ":global",
    ":int",
    ":short",
    ":character",
    ":float",
    ":double",
    ":word",
    "2",
    "1",
    "byte-size",
    "\"(typekey)\"",
    "vectorclass",
    ":slots",
    "(slotlist)",
    ":size",
    ":documentation",
    "make-class",
    "\"(self class &optional slots)\"",
    "\"(self class)\"",
    "\"(self class id)\"",
    ":offset",
    "\"(self class id &optional index)\"",
    "\"(self class id &optional index)\"",
    "\"(self class id &optional index)\"",
    "\"(self class val id &optional index)\"",
    "\"(struct-name &rest slotlist)\"",
    "\"(self class &optional (index 0))\"",
    "\"(self class val &optional (index 0))\"",
    "defcarray",
    "\"(array-name type &optional (size 1))\"",
    "vector",
    ":foreign",
    "make-foreign-string",
    "\"(addr size)\"",
    ":eusforeign",
    "\"@(#)$Id: eusforeign.l,v 1.2 2004/12/16 13:47:03 cvseus Exp $\"",
    "provide",
  };
