static pointer (*ftab[15])();

#define QUOTE_STRINGS_SIZE 126
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":test",
    "lisp::string-equal",
    ":rehash-size",
    "lisp::make-hash-table",
    "help::*method-list*",
    ":directory",
    "help::*eus-tex-dir*",
    "lisp::pathname",
    "lisp::pathname-directory",
    ":name",
    ":type",
    "\"tex\"",
    "lisp::make-pathname",
    ":direction",
    ":input",
    "lisp::open",
    "\"\"",
    "\"\"",
    "\"\"",
    "help::read-tex",
    "help::*help-hash*",
    ":size",
    "\"~a/euslisp.hlp\"",
    "\"~a\"",
    "\"nil\"",
    "\"help\"",
    "lisp::gethash",
    "\"~a command not found.  Commands alike are:~%\"",
    "lisp::apropos-list",
    "lisp::pprint",
    "\"NAME~%     ~a~%TYPE~%     \"",
    ":read-help",
    "0",
    "\"class~%\"",
    "2",
    "\"function~%\"",
    "3",
    "\"macro~%\"",
    "4",
    "\"constant~%\"",
    "5",
    "\"variable~%\"",
    "6",
    "\"special~%\"",
    "\"~a\"",
    "\"~a class is not found!\"",
    "\"~a method is not found in this class, but super-class may have.~%\"",
    "\"NAME~%     ~a~%TYPE~%     \"",
    "\"method~%CLASS~%     ~a ~%\"",
    "\"SYNOPSIS~%     ~a ~a ~%\"",
    "\"DESCRIPTION~%     ~a ~%\"",
    "\"DESCRIPTION~%     ~a ~%\"",
    "\"SUPER-CLASS~%     ~a ~%\"",
    "\"SLOTS~%     ~a ~%\"",
    "\"DESCRIPTION~%     ~a ~%\"",
    "\"~a\"",
    "\"~a class is not found~%\"",
    "\"CLASS NAME  : ~a ~%METHOD-LIST : \"",
    "\"~a~%              \"",
    "\"~a is not class.~%\"",
    "\"Usage : help &optional cmd class~%~%\"",
    "\"  cmd is a string that you wan to search. if you want to search method, you must specify class. but if you do not specify class, prints list of class that includes this method.~%\"",
    "\"This method is defined in classes as follows.~%\"",
    "\"~a ~a~%\"",
    "help::help-item",
    ":init",
    "lisp::sethash",
    "\"HELP\"",
    "\"HELP\"",
    "lisp::*package*",
    "\"no such package\"",
    "(lisp::help help-method load-help)",
    "help::*type-class*",
    ":constant",
    "help::*type-method*",
    "help::*type-func*",
    "help::*type-macro*",
    "help::*type-const*",
    "help::*type-var*",
    "help::*type-spec*",
    ":vtype",
    ":global",
    "help::*method-hash-list*",
    "\"~a/doc/~a/\"",
    "lisp::*eusdir*",
    "\"JA\"",
    "\"LANG\"",
    "lisp::substringp",
    "\"JP\"",
    "\"LANG\"",
    "\"jlatex\"",
    "\"latex\"",
    ":super",
    "lisp::object",
    ":slots",
    "(lisp::type lisp::fname help::seek lisp::count help::clas help::mhash)",
    ":metaclass",
    ":element-type",
    ":documentation",
    "lisp::make-class",
    "\"(self class typ fna see n &optional (c nil))\"",
    "\"(self class)\"",
    "lisp::help",
    "\"(&optional (cmd nil) (class nil) (hs t))\"",
    "help::print-item",
    "\"(cmd item param-list hs)\"",
    "help::print-item2",
    "\"(cmd item param-list hs)\"",
    "help::print-class",
    "\"(item param-list hs)\"",
    "help-method",
    "\"(class hs)\"",
    "help::help-usage",
    "\"(hs)\"",
    "help::help-method-list",
    "\"(cmd hs)\"",
    "load-help",
    "\"(helpfile)\"",
    "\"USER\"",
    "\"USER\"",
    "\"no such package\"",
    "\"HELP\"",
    "lisp::use-package",
    ":eushelp",
    "\"@(#)$Id: eushelp.l,v 1.1.1.1 2003/11/20 07:46:31 eus Exp $\"",
    "lisp::provide",
  };
