static pointer (*ftab[17])();

#define QUOTE_STRINGS_SIZE 78
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "cursor-pos",
    "erase-eol",
    "*terminal-io*",
    "cursor-backward",
    "cursor-forward",
    "list-delete",
    "list-insert",
    "nil",
    "line-edit",
    "cons",
    "\"~%~a\"",
    "tty-raw",
    "*line-edit-dispatch*",
    "tty-cooked",
    "string",
    "make-array",
    "*history*",
    "*history-max*",
    "*history-index*",
    "*history-sequence*",
    ":start1",
    ":start2",
    "replace",
    "x::*eustop-window*",
    ":update-history",
    "find-method",
    "\"~2d: ~A~%\"",
    "substringp",
    "make-string-input-stream",
    "evaluate-stream",
    "tty",
    "\"tty\"",
    "require",
    "(*line-edit-dispatch* refresh-line line-head line-left line-right line-delch line-delch-previous line-tail line-refresh line-insert line-null line-abort line-end line-edit *history-max* *history* *history-index* *history-sequence* new-history add-history print-history h get-history !)",
    ":vtype",
    ":global",
    "refresh-line",
    "\"(str start end)\"",
    "line-head",
    "\"(ch line index end)\"",
    "line-left",
    "\"(ch line index end)\"",
    "line-right",
    "\"(ch line index end)\"",
    "line-delch",
    "\"(ch line index end)\"",
    "line-delch-previous",
    "\"(ch line index end)\"",
    "line-tail",
    "\"(ch line index end)\"",
    "line-refresh",
    "\"(ch line index end)\"",
    "line-insert",
    "\"(ch line index end)\"",
    "line-clear",
    "\"(ch line index end)\"",
    "line-null",
    "\"(ch line index end)\"",
    "line-abort",
    "\"(ch line index end)\"",
    "line-end",
    "\"(ch line index end)\"",
    "\"line (string) is edited and returned\"",
    "new-history",
    "\"(n)\"",
    "add-history",
    "\"(h)\"",
    "print-history",
    "\"(&optional (strm *terminal-io*) &aux h)\"",
    "h",
    "\"print-history\"",
    "get-history",
    "\"(n)\"",
    "!",
    "\"(&optional (n 0))\"",
    ":history",
    "\"@(#)$Id: history.l,v 1.1.1.1 2003/11/20 07:46:31 eus Exp $\"",
    "provide",
  };
