static pointer (*ftab[5])();

#define QUOTE_STRINGS_SIZE 151
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "name",
    "*error-output*",
    "\"multiple defconstant for ~s: ~s --> ~s~%\"",
    ":variable-documentation",
    ":plist",
    ":remprop",
    ":home-package",
    "\"not a symbol\"",
    "*package*",
    "\"no string\"",
    "symbol",
    "#':function",
    ":function-documentation",
    "(variable :variable)",
    "(class :class)",
    ":class-documentation",
    "(method :method)",
    ":method-documentation",
    "\"T\"",
    "string",
    "*gentemp-index*",
    "adjoin",
    ":use",
    "symvector",
    ":find",
    "\"symbol conflict ~s in ~s\"",
    ":used-by",
    "delete",
    ":unused",
    ":test",
    "equal",
    "union",
    "\"symbol expected\"",
    ":enter",
    "\"~a cannot be imported due to symbol conflict\"",
    "homepkg",
    ":find-external",
    "\"symbol expected\"",
    ":name",
    ":nicknames",
    ":use-list",
    ":used-by-list",
    "package",
    ":unuse",
    "#(:nicknames :use)",
    "\"LISP\"",
    "if",
    "find-package",
    "setq",
    "error",
    "\"no such package\"",
    ":rename",
    ":shadow",
    ":import",
    "pname",
    "\"not a symbol\"",
    ":unintern",
    "\"no symbol\"",
    "car",
    "send-all",
    "\"~10a ~10a ~5d using=~a used-by=~a~%\"",
    "\"\"",
    "\"\"",
    "\"\"",
    "\"@(#)$Id: packsym.l,v 1.1.1.1 2003/11/20 07:46:31 eus Exp $\"",
    "\"LISP\"",
    "\"LISP\"",
    "\"no such package\"",
    "(symbol-plist remprop set symbol-package symbol-name make-symbol documentation gentemp packagep package-name package-nicknames package-use-list package-used-by-list use-package unuse-package make-package in-package rename-package shadow import symbol-string unintern package-stats)",
    "metaclass-name",
    "\"(x)\"",
    "\"(self class)\"",
    ":pname",
    "\"(self class)\"",
    ":func",
    "\"(self class)\"",
    ":value",
    "\"(self class val)\"",
    ":constant",
    "\"(self class c &optional (doc nil))\"",
    ":special",
    "\"(self class v &optional (doc nil))\"",
    ":global",
    "\"(self class v &optional doc)\"",
    ":vtype",
    "\"(self class &optional set)\"",
    ":init",
    "\"(self class pn &optional (vt 1))\"",
    "symbol-plist",
    "\"(sym)\"",
    "remprop",
    "\"(sym attr)\"",
    "symbol-package",
    "\"(sym)\"",
    "symbol-name",
    "\"(sym)\"",
    "make-symbol",
    "\"(str &optional (pkg *package*))\"",
    "documentation",
    "\"(sym &optional type)\"",
    "gentemp",
    "\"(&optional (prefix \\\"T\\\") (pkg *package*))\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class a)\"",
    "\"(self class pkg)\"",
    "\"(self class pkg)\"",
    "\"(self class pkg)\"",
    "\"(self class)\"",
    "\"(self class s)\"",
    "\"(self class &optional n)\"",
    ":hash",
    "\"(self class s)\"",
    "\"(self class sym)\"",
    "\"(self class s)\"",
    "\"(self class sym)\"",
    "\"(self class sym)\"",
    "\"(self class sym)\"",
    "\"(self class s)\"",
    ":unexport",
    "\"(self class sym)\"",
    "package-name",
    "\"(pkg)\"",
    "package-nicknames",
    "\"(pkg)\"",
    "package-use-list",
    "\"(pkg)\"",
    "package-used-by-list",
    "\"(pkg)\"",
    "packagep",
    "\"(pkg)\"",
    "use-package",
    "\"(pkg &optional (curpkg *package*))\"",
    "unuse-package",
    "\"(pkg &optional (curpkg *package*))\"",
    "make-package",
    "\"(pkgname &key (nicknames) (use (list \\\"LISP\\\")))\"",
    "in-package",
    "\"(pkgname)\"",
    "rename-package",
    "\"(pkg new-name &optional new-nicks)\"",
    "shadow",
    "\"(sym &optional (pkg *package*))\"",
    "import",
    "\"(x &optional (pkg *package*))\"",
    "symbol-string",
    "\"(s)\"",
    "unintern",
    "\"(s &optional (pkg *package*))\"",
    "package-stats",
    "\"(&optional (s t) &aux use used)\"",
  };
