static pointer (*ftab[10])();

#define QUOTE_STRINGS_SIZE 202
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "pname",
    "((\"space\" 32) (\"rubout\" 127) (\"delete\" 127) (\"newline\" 10) (\"linefeed\" 10) (\"page\" 12) (\"formfeed\" 12) (\"backspace\" 8) (\"return\" 13) (\"esc\" 27) (\"escape\" 27) (\"bell\" 7) (\"tab\" 9) (\"null\" 0) (\"soh\" 1) (\"stx\" 2) (\"etx\" 3) (\"left-paren\" 40) (\"right-paren\" 41) (\"lparen\" 40) (\"rparen\" 41))",
    ":test",
    "string-equal",
    "assoc",
    "\"unknown # code\"",
    "princ-to-string",
    "\"cannot coerce to string \"",
    "string",
    "position",
    "#(:start :end)",
    "\"no string\"",
    "#(:start :end)",
    "\"no string\"",
    "#(:start :end)",
    ":start",
    ":end",
    "#(:start :end)",
    "#(:start1 :end1 :start2 :end2)",
    "stringeq",
    "#(:start1 :end1 :start2 :end2)",
    "stringequal",
    ":start2",
    ":end2",
    "((:short . 2) (:long . 4) (:byte . 1) (:char . 1) (:int . 4) (:integer . 4) (:float . 4) (:double . 8))",
    "flatten",
    "zerop",
    "\"\"",
    "\"\"",
    ":root",
    "\"HOME\"",
    "\"..\"",
    "\"/\"",
    "\"/\"",
    "concatenate",
    ":directory-string",
    "\".\"",
    "host",
    "device",
    "directory",
    "name",
    "type",
    "version",
    "\"#P~S\"",
    ":namestring",
    "#(:host :device :directory :name :type :version)",
    "pathname",
    ":parse-namestring",
    "\"not a pathname ~s\"",
    "#(:host :device :directory :name :type :version :defaults)",
    ":init",
    ":host",
    ":device",
    ":directory",
    ":name",
    ":type",
    ":version",
    ":merge",
    "\"\"",
    "*default-pathname-defaults*",
    "namestring",
    "\"/\"",
    "\"cannot locate the file\"",
    "\"#<~a #x~x \\\"~a\\\">\"",
    ":string",
    "\"~a://~a:~a~a\"",
    "\"~a://~a~a\"",
    "connect-server",
    "\"http\"",
    "read-from-string",
    "super",
    "(:root)",
    "\"cannot parse url ~a\"",
    "url-pathname",
    "\"http\"",
    "(:root)",
    "\"cannot parse url ~a\"",
    "\"~d\"",
    "\"~a~2a~2a~2a.~a\"",
    "\"~a~2a~3A~2a.~a\"",
    "((0 \"Jan\") (1 \"Feb\") (2 \"Mar\") (3 \"Apr\") (4 \"May\") (5 \"Jun\") (6 \"Jul\") (7 \"Aug\") (8 \"Sep\") (9 \"Oct\") (10 \"Nov\") (11 \"Dec\"))",
    "\"~a~a.~a\"",
    "\"@(#)$Id: string.l,v 1.1.1.1 2003/11/20 07:46:31 eus Exp $\"",
    "\"LISP\"",
    "\"LISP\"",
    "*package*",
    "\"no such package\"",
    "(true-string string make-string string-left-trim string-right-trim string-trim nstring-downcase nstring-upcase string-upcase string-downcase string= string-equal substringp pathname pathnamep pathname namestring pathname-directory pathname-name pathname-type directory-namestring make-pathname parse-namestring *default-pathname-defaults* null-string-p merge-pathnames concatenate-pathnames truename url-pathname parse-url sequential-file-name dated-file-name timed-file-name digits-string)",
    "read_sharp_backslash",
    "\"(strm char num)\"",
    "true-string",
    "\"(s)\"",
    "\"(x)\"",
    "make-string",
    "\"(size)\"",
    "string-left-trim",
    "\"(bag str)\"",
    "string-right-trim",
    "\"(bag str)\"",
    "string-trim",
    "\"(bag str)\"",
    "nstring-downcase",
    "\"(str &key (start 0) (end (length str)))\"",
    "nstring-upcase",
    "\"(str &key (start 0) (end (length str)))\"",
    "string-upcase",
    "\"(str &key (start 0) (end))\"",
    "string-downcase",
    "\"(str &key (start 0) (end))\"",
    "string=",
    "\"(str1 str2 &key (start1 0) (end1 100000000) (start2 0) (end2 100000000))\"",
    "\"(str1 str2 &key (start1 0) (end1 100000000) (start2 0) (end2 100000000))\"",
    "substringp",
    "\"(sub str)\"",
    ":get",
    "\"(self class pos type)\"",
    ":set",
    "\"(self class val pos type)\"",
    ":global",
    ":super",
    "object",
    ":slots",
    "(host device directory name type version)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "(pathname-host pathname-device pathname-directory pathname-name pathname-type pathname-version)",
    "explode-directory-names",
    "\"(dirnames)\"",
    "\"(self class pn)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class &optional h)\"",
    "\"(self class &optional d)\"",
    "\"(self class &optional d)\"",
    "\"(self class &optional n)\"",
    "\"(self class &optional tp)\"",
    ":set-type",
    "\"(self class tp)\"",
    "\"(self class &optional v)\"",
    "\"(self class defaults)\"",
    ":add-directory",
    "\"(self class d)\"",
    ":prin1",
    "\"(self class &optional (strm t))\"",
    "\"(self class &key ((:host hst)) ((:device dev)) ((:directory dir)) ((:name nm)) ((:type tp)) ((:version vers)))\"",
    "pathnamep",
    "\"(p)\"",
    "\"(p)\"",
    "\"(p)\"",
    "pathname-directory",
    "\"(s)\"",
    "pathname-name",
    "\"(s)\"",
    "pathname-type",
    "\"(s)\"",
    "directory-namestring",
    "\"(s)\"",
    "make-pathname",
    "\"(&key host device directory name type version defaults)\"",
    "parse-namestring",
    "\"(pn)\"",
    "\"\"",
    "\"\"",
    "\"\"",
    "\"l\"",
    "null-string-p",
    "\"(s)\"",
    "merge-pathnames",
    "\"(pathnam &optional (defaults *default-pathname-defaults*))\"",
    "concatenate-pathnames",
    "\"(&rest paths)\"",
    "truename",
    "\"BUG: (truename \\\"/a/\\\") returns #P\\\"/a/NIL\\\"\"",
    "(protocol server port)",
    "\"(self class strm)\"",
    "\"(self class)\"",
    ":string2",
    "\"(self class)\"",
    ":port",
    "\"(self class &optional p)\"",
    ":server",
    "\"(self class &optional s)\"",
    ":connect",
    "\"(self class &optional (time-out 5))\"",
    "\"(self class &optional s)\"",
    ":protocol",
    "\"(self class &optional proto)\"",
    "\"(self class url-string)\"",
    "\"(p)\"",
    "parse-url",
    "\"(url-string)\"",
    "digits-string",
    "\"(n digits &optional (base 10))\"",
    "timed-file-name",
    "\"(head extension &optional (dt (unix:localtime)))\"",
    "dated-file-name",
    "\"(head extension &optional (dt (unix:localtime)))\"",
    "sequential-file-name",
    "\"(head num extension &optional (digits 4))\"",
  };
