static pointer (*ftab[21])();

#define QUOTE_STRINGS_SIZE 144
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "*timer-job-count*",
    "\" 	\"",
    "position",
    "*standard-input*",
    "*input-line*",
    "make-string-input-stream",
    "\"interrupt\"",
    "warning-message",
    "unix:ualarm",
    "*replevel*",
    "\"B\"",
    "*reptype*",
    "toplevel-prompt",
    "*signal-handlers*",
    "\"signal ~s ~s~%\"",
    "\"S\"",
    "-",
    "string",
    "*package*",
    "\"no such package\"",
    "*try-unix*",
    "unix:system",
    "buffer",
    "\"?~%\"",
    "warn",
    "*history*",
    "\"~d.\"",
    "*history-sequence*",
    "\"~A~D-\"",
    "*user-package*",
    "\"~A:\"",
    "package-name",
    "\"~a$ \"",
    "*prompt-string*",
    ":buffer",
    "\"~s\"",
    "add-history",
    "*toplevel-hook*",
    "eval-dynamic",
    "*unbound*",
    "\"?\"",
    "++",
    "+++",
    "+",
    "**",
    "***",
    "*",
    "*prompt*",
    "functionp",
    "\"~a\"",
    "*terminal-io*",
    "euserror",
    "*error-handler*",
    ":reploop",
    ":reploop-select",
    "*top-selector*",
    ":add-port",
    "repsel",
    ":select",
    "*top-selector-interval*",
    "*timer-job*",
    "*use-top-selector*",
    "*error-output*",
    "\"~C[1;3~Cm~A error: ~A\"",
    "*program-name*",
    "\" ~A\"",
    "\" in ~s\"",
    "\"~C[0m~%\"",
    "\"E\"",
    "\"~%~A\"",
    "lisp-implementation-version",
    "sigint-handler",
    "eussig",
    "unix:tcgets",
    "*tc*",
    "*history-max*",
    "new-history",
    "find-executable",
    "*symbol-input*",
    "\"USER\"",
    "*user*",
    "*eustop-argument*",
    "pathname-name",
    "\"EUSRC\"",
    "\"HOME\"",
    "\"/.eusrc\"",
    "probe-file",
    ":verbose",
    "load",
    "\".eusrc\"",
    "\".eusrc\"",
    "\"euscomp\"",
    "compiler::comp-file-toplevel",
    "exit",
    "*eustop-hook*",
    "read-from-string",
    ":eusexit",
    "\"\"",
    "\"LISP\"",
    "\"LISP\"",
    "\"no such package\"",
    "(- * ** *** + ++ +++ *replevel* *reptype* *input-line* *prompt* *prompt-string* *history* *try-unix* skip-blank read-list-from-line sigint-handler *signal-handlers* *eustop-hook* *toplevel-hook* *top-selector* *timer-job* *top-selector-interval* evaluate-stream reploop euserror eustop reset toplevel-prompt)",
    ":vtype",
    ":global",
    "toplevel-streams",
    "toplevel-streams-bitvec",
    ":special",
    "\"\"",
    "\"eus\"",
    "port-selector",
    ":init",
    "count-up-timer",
    "\"NO_TOP_SELECTOR\"",
    "\"nil\"",
    "skip-blank",
    "\"(s &optional (eof (gensym)))\"",
    "read-list-from-line",
    "\"(&optional (s *standard-input*) (eof (gensym)))\"",
    "\"(sig code)\"",
    "vector",
    "make-sequence",
    "\"(sig &rest code &aux (handler (aref *signal-handlers* sig)))\"",
    "evaluate-stream",
    "\"(input)\"",
    "\"(strm)\"",
    "rep1",
    "\"(repstream eof local-bindings &optional (ttyp t))\"",
    "prompt",
    "\"(strm)\"",
    "reploop-non-select",
    "\"(&optional (repstream *terminal-io*) (ttyp (unix:isatty repstream)))\"",
    "\"(repstream eof ttyp local-bindings)\"",
    "reploop-select",
    "\"(&optional (repstream *terminal-io*) (ttyp (unix:isatty repstream)))\"",
    "reploop",
    "\"(prompt &optional (repstream *terminal-io*) (ttyp (unix:isatty repstream)))\"",
    "\"(code msg1 form &optional (msg2))\"",
    "eustop",
    "\"(&rest argv)\"",
    "reset",
    "\"(&optional (n 0))\"",
    ":toplevel",
    "\"@(#)$Id: toplevel.l,v 1.1.1.1 2003/11/20 07:46:31 eus Exp $\"",
    "provide",
  };
