static pointer (*ftab[2])();

#define QUOTE_STRINGS_SIZE 34
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "*tc*",
    "unix:tcsets",
    "*terminal-io*",
    "\"~c~c~dA\"",
    "\"~c~c~dB\"",
    "\"~c~c~dC\"",
    "\"~c~c~dD\"",
    "\"~c\"",
    "\"~c~c~c~DC\"",
    "\"~c~cK\"",
    "(tty-raw tty-cooked backspace cursor-up cursor-down cursor-backward cursor-forward cursor-return cursor-pos erase-eol)",
    "tty-raw",
    "\"(&optional (port 0))\"",
    "tty-cooked",
    "\"(&optional (port 0))\"",
    "backspace",
    "\"(&optional (n 1))\"",
    "cursor-up",
    "\"(&optional (n 1))\"",
    "cursor-down",
    "\"(&optional (n 1))\"",
    "cursor-forward",
    "\"(&optional (n 1))\"",
    "cursor-backward",
    "\"(&optional (n 1))\"",
    "cursor-return",
    "\"nil\"",
    "cursor-pos",
    "\"(x)\"",
    "erase-eol",
    "\"nil\"",
    ":tty",
    "\"@(#)$Id: tty.l,v 1.1.1.1 2003/11/20 07:46:31 eus Exp $\"",
    "provide",
  };
