static pointer CLO565();
static pointer CLO566();
static pointer CLO600();
static pointer CLO613();
static pointer (*ftab[10])();

#define QUOTE_STRINGS_SIZE 55
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":width",
    ":height",
    ":depth",
    ":entity",
    "make-string",
    "\"not supported depth\"",
    "image:color-image24",
    ":init",
    "image:read-pnm-file",
    "image:color-to-deep",
    "\"not supported depth\"",
    "gluscaleimage",
    "max",
    "+",
    "#(:top :bottom :side0 :side1 :side2 :side3 :texture-width :texture-height)",
    "\"make-cube-with-texture: argument error\"",
    "geometry:make-cube",
    ":get-face",
    ":top",
    ":bottom",
    ":side",
    "null",
    "remove-if",
    "append-image",
    "\";; rescaling image to ~ax~a (original: ~ax~a)~%\"",
    "warn",
    ":test",
    "equal",
    "make-hash-table",
    ":vertices",
    "sethash",
    "\"make-cube-with-texture-\"",
    "symbol-string",
    ":gl-texture2",
    ":gl-texture-image-w",
    ":gl-texture-image-h",
    ":gl-texture-image-d",
    ":gl-texture-image",
    ":gl-texturecoordinate2",
    "\"GL\"",
    "\"GL\"",
    "*package*",
    "\"no such package\"",
    "(load-texture-file append-image make-cube-with-texture)",
    "transpose-rows",
    "\"(img)\"",
    "load-texture-file",
    "\"(file)\"",
    "\"(&rest images)\"",
    "(make-cube-with-texture)",
    "make-cube-with-texture",
    "\"(xsize ysize zsize &rest args &key top bottom side0 side1 side2 side3 texture-width texture-height &allow-other-keys)\"",
    ":gltexture",
    "\"@(#)$Id: gltexture.l,v 1.1.1.1 2003/11/20 07:46:32 eus Exp $\"",
    "provide",
  };
