static pointer (*ftab[1])();

#define QUOTE_STRINGS_SIZE 38
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":glxconst",
    "provide",
    "\"GL\"",
    "\"GL\"",
    "*package*",
    "\"no such package\"",
    "(glx_use_gl glx_buffer_size glx_level glx_rgba glx_doublebuffer glx_stereo glx_aux_buffers glx_red_size glx_green_size glx_blue_size glx_alpha_size glx_depth_size glx_stencil_size glx_accum_red_size glx_accum_green_size glx_accum_blue_size glx_accum_alpha_size glx_bad_screen glx_bad_attribute glx_no_extension glx_bad_visual glxbadcontext glxbadcontextstate glxbaddrawable glxbadpixmap glxbadcontexttag glxbadcurrentwindow glxbadrenderrequest glxbadlargerequest glxunsupportedprivaterequest)",
    "glx_use_gl",
    ":constant",
    "glx_buffer_size",
    "glx_level",
    "glx_rgba",
    "glx_doublebuffer",
    "glx_stereo",
    "glx_aux_buffers",
    "glx_red_size",
    "glx_green_size",
    "glx_blue_size",
    "glx_alpha_size",
    "glx_depth_size",
    "glx_stencil_size",
    "glx_accum_red_size",
    "glx_accum_green_size",
    "glx_accum_blue_size",
    "glx_accum_alpha_size",
    "glx_bad_screen",
    "glx_bad_attribute",
    "glx_no_extension",
    "glx_bad_visual",
    "glxbadcontext",
    "glxbadcontextstate",
    "glxbaddrawable",
    "glxbadpixmap",
    "glxbadcontexttag",
    "glxbadcurrentwindow",
    "glxbadrenderrequest",
    "glxbadlargerequest",
    "glxunsupportedprivaterequest",
  };
