static pointer FLET639();
static pointer CLO640();
static pointer CLO641();
static pointer (*ftab[3])();

#define QUOTE_STRINGS_SIZE 56
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "\"#Inventor V1.0 ascii~%\"",
    "\"Separator {~%~%\"",
    "\" ShapeHints {~%\"",
    "\"    hints (SURFACE | ORDERED)~%\"",
    "\" }~%~%\"",
    "\"  Group {~%\"",
    "body",
    ":gl-material",
    "\"  Material {~%\"",
    "\"    ambientColor ~a ~a ~a~%\"",
    "\"    diffuseColor ~a ~a ~a~%\"",
    "\"    specularColor ~a ~a ~a~%\"",
    "\"    emissiveColor ~a ~a ~a~%\"",
    "\"    shininess ~a~%\"",
    "\"    transparency ~a~%\"",
    "\"  }~%\"",
    "\"    Coordinate3 {~%\"",
    "\"         point [~%\"",
    "\"            ~a ~a ~a,~%\"",
    "*scale*",
    "\"        ]~%\"",
    "\"    }~%\"",
    "\"    Normal {~%\"",
    "\"      vector [~%\"",
    "\"            ~a ~a ~a,~%\"",
    "\"       ]~%\"",
    "\"    }~%\"",
    "\"   NormalBinding {~%\"",
    "\"      value PER_FACE~%\"",
    "\"   }~%\"",
    "\"IndexedFaceSet {~%\"",
    "\"   coordIndex [~%\"",
    "\"~a, \"",
    "\"~a,~%\"",
    "\"   ]~%\"",
    "\"  }~%\"",
    "\" }~%\"",
    "\"}~%\"",
    "append",
    ":drawners",
    "find-method",
    ":worldcoords",
    ":faces",
    ":vertices",
    ":normal",
    ":geoclasses",
    "\"lisp/geo/geoclasses.l\"",
    "require",
    ":gldecl",
    "\"lisp/opengl/src/gldecl.l\"",
    ":vtype",
    ":global",
    "toiv",
    "\"(file &rest bodies)\"",
    ":toiv",
    "provide",
  };
