/*
 *   This file was automatically generated by version 1.6 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Apr 25 14:11:52 1996
 */

#include "eus.h"

extern void glClearColorfv (eusfloat_t v[4]);
extern void glOrtho6f (eusfloat_t left, eusfloat_t right, eusfloat_t bottom, eusfloat_t top, eusfloat_t near, eusfloat_t far);
extern void glOrthofv (eusfloat_t v[6]);
extern void glRotatefv (eusfloat_t v[4]);
extern void glTranslatefv (eusfloat_t v[3]);
extern void auxSolidTeapotfv (eusfloat_t v[1]);
extern void glClipPlanef (eusinteger_t pl, eusfloat_t eqn[4]);
extern void auxSolidSpherefv (eusfloat_t v[1]);
extern void auxWireSpherefv (eusfloat_t v[1]);
extern void auxSolidCylinderfv (eusfloat_t v[2]);
extern void auxSolidConefv (eusfloat_t v[2]);
extern void auxSolidBoxfv (eusfloat_t v[3]);
extern void gluPerspectivefv (eusfloat_t v[4]);
extern void gluLookAtfv (eusfloat_t v[9]);
extern void gluTessCallbackl (eusinteger_t *tobj, eusinteger_t which, eusinteger_t fn, eusinteger_t fn2);
extern void auxSolidTorusfv (eusfloat_t v[2]);
extern void auxSolidCubefv (eusfloat_t v[1]);
extern void auxSolidOctahedronfv (eusfloat_t v[1]);
extern void glClearAccumfv (eusfloat_t v[4]);
extern void glAccumfv (eusinteger_t op, eusfloat_t v[1]);
extern void gluDiskfv (eusinteger_t qobj, eusfloat_t v[4]);
extern void gluPartialDiskfv (eusinteger_t *qobj, eusfloat_t v[6]);
extern void auxWireIcosahedronfv (eusfloat_t v[1]);
extern void glScalefv (eusfloat_t v[3]);
extern void gluNurbsPropertyfv (eusinteger_t nobj, eusinteger_t property, eusfloat_t *value);
extern void glMapGrid2fv (eusfloat_t v[6]);
extern void glBitmapfv (eusinteger_t w, eusinteger_t h, eusfloat_t v[4], eusinteger_t b);
extern void glMap1fv (eusinteger_t target, eusfloat_t args[4], eusinteger_t points);
extern void glMap2fv (eusinteger_t target, eusfloat_t args[8], eusinteger_t points);
extern void auxSetOneColorfv (int color, GLfloat v[3]);
extern void glFrustumfv (eusfloat_t v[6]);
extern void gluOrtho2Dfv (eusfloat_t v[4]);
extern void glPointSizefv (eusfloat_t v[1]);
extern void glClearIndexfv (eusfloat_t v[1]);
extern eusinteger_t alloctessinfo (eusfloat_t vert[3], eusinteger_t tp, eusfloat_t tcoord[2], eusinteger_t np, eusfloat_t ncoord[2]);
extern void tess_vertex_cb (eusinteger_t i);
extern void glDepthRangefv (eusfloat_t clamp[2]);
extern void glPolygonOffsetEXTfv (GLfloat v[2]);

