CFLAGS = -O

OBJ = cone.o ssvdc.o amax1.o max0.o min0.o srot.o srotg.o sdot.o \
      snrm2.o sscal.o sswap.o saxpy.o \
      rank.o mat_mult.o edge.o hash5.o same.o \
      cone_pre.o cone_post.o \
      face_init.o face.o update_edge.o fugo_calc.o \
      cone_inter.o convexconeref.o

$(OBJ) : arith.h

lib: $(OBJ)
	ld -shared -o libconvexcone.so $(OBJ)
