# CAUTION! Please make on Sun-3, not Sun-4
juman:	eus-manual.tex preface.tex object.tex \
	vector-matrix.tex geometry.tex perspective.tex
	jlatex eus-manual
	jlatex eus-manual
	ptex -Piclw eus-manual
