static pointer (*ftab[11])();

#define QUOTE_STRINGS_SIZE 56
const static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "*motion-threshold*",
    "unit-matrix",
    "entity",
    "matrix-column",
    ":start1",
    ":end1",
    "replace",
    "matrix-row",
    "matrix",
    "float-vector",
    "*maxrank*",
    "*maxcp*",
    "no-constraints-found",
    "too-many-constraints-found-to-solve",
    "car",
    "solve-cone",
    "error-no-motions-found",
    ":test",
    "eqmotion",
    ":test-not",
    ":key",
    "member",
    "inequalities",
    "provide",
    "\"GEOMETRY\"",
    "\"GEOMETRY\"",
    "*package*",
    "\"no such package\"",
    ":geoclasses",
    "\"geoclasses.l\"",
    "require",
    "\";;;; solve-inequalities v1.07 Jan.17.1992.~%\"",
    "(eqmotion norm-difv make-jacobian-world-pos make-jacobian-world make-inequalities solve-inequalities constrained-motion constrained-force solve-cone convexcone-module)",
    ":global",
    "\"(x y)\"",
    "norm-difv",
    "\"(v)\"",
    "make-jacobian-world-pos",
    "\"(pos)\"",
    "make-jacobian-world",
    "\"(pos)\"",
    "make-inequalities",
    "\"(clists)\"",
    "convexcone-module",
    "\"clib/libconvexcone.so\"",
    "load-foreign",
    "\"cone_inter\"",
    "nil",
    ":integer",
    "make-foreign-code",
    "solve-inequalities",
    "\"(inequalities)\"",
    "constrained-motion",
    "\"(constraint)\"",
    "constrained-force",
    "\"(motion)\"",
  };
