static pointer (*ftab[9])();

#define QUOTE_STRINGS_SIZE 47
const static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "*motion-threshold*",
    "unit-matrix",
    "*scale-rotation*",
    "entity",
    "matrix-column",
    ":start1",
    ":end1",
    "replace",
    "matrix-row",
    "matrix",
    "float-vector",
    "*maxrank*",
    "too-many-constraints-found-to-solve",
    "car",
    "projection",
    "\"GEOMETRY\"",
    "\"GEOMETRY\"",
    "*package*",
    "\"no such package\"",
    ":geoclasses",
    "\"geoclasses.l\"",
    "require",
    "\";;;; projection v1.00 Sep.13,1996.~%\"",
    "(eqmotion norm-difv make-jacobian-world-pos make-jacobian-world make-inequalities find-projection possible-motion projection projection-module)",
    ":global",
    "*maxcp*",
    "eqmotion",
    "\"(x y)\"",
    "norm-difv",
    "\"(v)\"",
    "make-jacobian-world-pos",
    "\"(pos)\"",
    "make-jacobian-world",
    "\"(pos)\"",
    "make-inequalities",
    "\"(clists)\"",
    "projection-module",
    "\"clib3/libprojection.so\"",
    "load-foreign",
    "\"projection_inter\"",
    "nil",
    ":integer",
    "make-foreign-code",
    "find-projection",
    "\"(motion-in inequalities)\"",
    "possible-motion",
    "\"(motion-in clist)\"",
  };
