static pointer UWP3506();
static pointer (*ftab[24])();

#define QUOTE_STRINGS_SIZE 255
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":create-item",
    "button-item",
    "\"ok\"",
    ":ok",
    "\"cancel\"",
    ":cancel",
    "\"cd\"",
    ":open",
    "\"go-up\"",
    ":go-up",
    "\"view\"",
    ":view",
    "text-item",
    "\"file:\"",
    ":columns",
    ":font",
    "font-courb12",
    "\"cwd:\"",
    "scrolltextwindow",
    ":create",
    ":parent",
    ":width",
    ":height",
    ":scroll-bar",
    ":horizontal-scroll-bar",
    ":map",
    ":notify-object",
    ":notify-method",
    ":file-selected",
    "truename",
    ":display-strings",
    ":locate-item",
    ":value",
    "namestring",
    "#(:font :directory :ok-notify :cancel-notify)",
    "string",
    "pwd",
    "\"/\"",
    "send-message",
    "super",
    ":event-mask",
    "(:configure)",
    ":create-buttons",
    ":create-fileview",
    ":selection",
    "position",
    ":cwd",
    "merge-pathnames",
    "event",
    ":selected-fname",
    "probe-file",
    "textviewpanel",
    ":file",
    ":destroy",
    "send",
    "lisp::directory-p",
    "\"/\"",
    "\"\"",
    ":clear",
    ":directory",
    "pathname-directory",
    "make-pathname",
    "\"\"",
    ":resize",
    "/=",
    "\"load\"",
    ":load",
    "\"remove\"",
    ":remove",
    "\"print\"",
    ":print",
    "\"compile\"",
    ":compile",
    "\"eval:\"",
    ":eval",
    "confirmpanel",
    "load",
    "read-from-string",
    "\"a2ps ~a | lpr \"",
    "compiler:compile-file",
    ":ask",
    ":remove-confirm",
    "\"Do you really want to delete\"",
    "\" ?\"",
    ":yes",
    "#(:font :file :strings :sexp :width)",
    "(:configure)",
    "\"quit\"",
    ":quit",
    "\"print\"",
    "\"find\"",
    ":find",
    "\"find: \"",
    ":read-file",
    ":flush",
    ":window-main-loop",
    ":lines",
    "\"/tmp/eus.~a.~d\"",
    ":name",
    ":direction",
    ":output",
    "open",
    "\"~a~%\"",
    "\"a2ps ~a | lpr \"",
    ":nlines",
    ":line",
    "substringp",
    ":display-selection",
    ":locate",
    "\".\"",
    "\"ls\"",
    "\"-la\"",
    "piped-fork",
    "\" \"",
    "\"??\"",
    "\"~18a ~a\"",
    "font-courb18",
    ":background",
    "\"#ff6040\"",
    "\"YES\"",
    "\"NO\"",
    ":no",
    ":move",
    ":image-string",
    ":draw-message",
    ":unmap",
    "event-width",
    "event-height",
    "font-courb14",
    "\"OK\"",
    "\"Cancel\"",
    "\"Ambient\"",
    ":ambient",
    "\"Diffuse\"",
    ":diffuse",
    "\"Specular\"",
    ":specular",
    "\"Emission\"",
    ":emission",
    "\"Shininess\"",
    ":shininess",
    "\"Transparency\"",
    ":transparency",
    "slider-item",
    "\"value1\"",
    ":value1",
    "\"value2\"",
    ":value2",
    "\"value3\"",
    ":value3",
    "#(:width :height)",
    "\"obj: \"",
    ":set-object",
    "\"class: \"",
    ":set-class",
    "\"sub\"",
    ":set-subclass",
    "\"super\"",
    ":set-superclass",
    ":y",
    "textwindow",
    "make-textwindow-stream",
    "car",
    ":methods",
    "mmm",
    "view-window",
    "\"~s ~s~%\"",
    "\"object ~s is unbound~%\"",
    "\"class ~s is unbound~%\"",
    "\"~a\"",
    ":superclasses",
    ":update-method-names",
    "member",
    ":xdecl",
    "\"Xdecl.l\"",
    "require",
    "(filedialog filepanel)",
    "filedialog",
    ":global",
    ":super",
    "panel",
    ":slots",
    "(current-dir cd-button cdir-text fname-text file-win file-win-offset ok-button cancel-button view-button goup-button oknotify cancelnotify)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "\"(self class)\"",
    "\"(self class directory)\"",
    "\"(self class &rest args &key (font font-courb12) (directory (concatenate string (pwd) \\\"/\\\")) (ok-notify) (cancel-notify ok-notify) &allow-other-keys)\"",
    "\"(self class)\"",
    "\"(self class line)\"",
    "\"(self class)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class w h)\"",
    ":configurenotify",
    "\"(self class event)\"",
    "filepanel",
    "(print-button remove-button find-button load-button compile-button eval-text confirm-win file-being-removed)",
    "\"(self class)\"",
    "\"(self class &rest args)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class answer)\"",
    "(quit-button find-button print-button file-name finish-button find-text view-window)",
    "\"(self class &rest args &key font file strings (sexp) (width 400) &allow-other-keys)\"",
    "\"(self class event)\"",
    ":finish",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class w h)\"",
    "\"(self class event)\"",
    "ls-l",
    "\"(&optional (dir \\\".\\\"))\"",
    "(yes-button no-button answer message notify-object notify-method)",
    "\"(self class &rest args)\"",
    "\"(self class)\"",
    "\"(self class rcv meth &rest lines)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "colorpickerpanel",
    "(ok-button cancel-button ambient-button diffuse-button specular-button emission-button slider1 slider2 slider3 shininess-button transparency-button ambient-value diffuse-value specular-value emission-value shininess-value transparency-value reply-object reply-method)",
    "\"(self class &rest args)\"",
    ":init-value",
    "\"(self class colmat)\"",
    "\"(self class item v)\"",
    "\"(self class item v)\"",
    "\"(self class item v)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "objectbrowser",
    "(object-text class-text super-button sub-button view-panel msg-win msg-stream current-object current-class class-tree methods method-names)",
    "\"(self class &rest args &key (width 350) (height 500) &allow-other-keys)\"",
    "\"(self class &optional (klass current-class))\"",
    "\"(self class evnt)\"",
    "\"(self class evnt)\"",
    "\"(self class item)\"",
    "\"(self class item)\"",
    ":xapplwin",
    "\"@(#)$Id: Xapplwin.l,v 1.1.1.1 2003/11/20 07:46:33 eus Exp $\"",
    "provide",
  };
