static pointer (*ftab[14])();

#define QUOTE_STRINGS_SIZE 134
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "send-message",
    "super",
    ":create",
    "menu-panel",
    ":create-item",
    "button-item",
    "\"red\"",
    ":color-event",
    "*color-map*",
    ":alloc",
    "\"blue\"",
    "\"green\"",
    "\"clear\"",
    ":clear-event",
    "\"white back\"",
    ":background-event",
    "\"lightgray back\"",
    "\"darkgray back\"",
    "\"black back\"",
    ":draw-rectangle",
    "event",
    "event-button",
    ":function",
    ":xor",
    ":foreground",
    "event-pos",
    ":draw-selection-rectangle",
    ":popup",
    "event-x-root",
    "event-y-root",
    "event-state",
    ":left",
    "member",
    ":right",
    ":motionnotify",
    ":control",
    ":clear",
    ":copy",
    "*buttonrelease-wanted*",
    ":buttonrelease",
    ":background",
    "#(:max :min :background :lines :colors :color)",
    "*blackpixel*",
    "*whitegc*",
    ":new-pixmap",
    ":range",
    ":lines",
    ":colors",
    ":initial-element",
    "gcontext",
    "make-color-gc",
    "make-array",
    "xpixmap",
    ":width",
    ":height",
    ":graph",
    ":copy-from",
    "*display*",
    "copyarea",
    "cleararea",
    ":line",
    "zerop",
    ":resize",
    ":flush",
    "send",
    "#(:pixmap)",
    "xwindow",
    ":parent",
    "xscroll-bar",
    "xhorizontal-scroll-bar",
    ":reset-subwindows",
    ":set-pixmap",
    ":move",
    "\":scroll n=~s srcy=~s desty=~s erasey=~s~%\"",
    ":source-x",
    ":source-y",
    ":x",
    ":y",
    ":clear-area",
    "\"X\"",
    "\"X\"",
    "*package*",
    "\"no such package\"",
    ":xdecl",
    "\"Xdecl.l\"",
    "require",
    "canvas",
    "\"(self class &rest args)\"",
    ":selection",
    "\"(self class)\"",
    ":adjust-corners",
    "\"(self class)\"",
    "\"(self class)\"",
    ":buttonpress",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class e)\"",
    "\"(self class color e)\"",
    "\"(self class color e)\"",
    "graph-canvas",
    ":global",
    ":super",
    ":slots",
    "(pixmap ymax ymin prev-y graph-args xinc yinc gcs count)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "\"(self class &rest args &key (max 1.0) (min -1.0) (background *blackpixel*) (lines 1) (colors) (color *whitegc*) &allow-other-keys)\"",
    "\"(self class &optional (w width) (h height))\"",
    "\"(self class max &optional (min 0.0))\"",
    "\"(self class n)\"",
    "\"(self class cs)\"",
    "\"(self class &rest args)\"",
    ":incremental-graph",
    "\"(self class new-values)\"",
    "\"(self class)\"",
    "\"(self class x y)\"",
    ":redraw",
    "\"(self class)\"",
    "(pixmap-scroller)",
    "pixmap-scroller",
    "panel",
    "(pixwin vscroll hscroll pixmap start-x start-y pix-width pix-height)",
    "\"(self class &rest args &key pixmap &allow-other-keys)\"",
    "\"(self class)\"",
    "\"(self class pmap)\"",
    ":scroll",
    "\"(self class &optional (n 1) &aux srcy desty erasey)\"",
    ":xcanvas",
    "\"@(#)$Id: Xcanvas.l,v 1.1.1.1 2003/11/20 07:46:34 eus Exp $\"",
    "provide",
  };
