static pointer CLO3163();
static pointer CLO3164();
static pointer CLO3165();
static pointer CLO3174();
static pointer CLO3179();
static pointer (*ftab[3])();

#define QUOTE_STRINGS_SIZE 63
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "#(:font :border-width :width :color)",
    "font-cour12",
    "*bisque1*",
    "send-message",
    "super",
    ":create",
    ":font",
    ":color",
    ":height",
    ":border-width",
    ":map",
    ":override-redirect",
    ":event-mask",
    "(:enterleave :configure)",
    ":label",
    "string-equal",
    "max",
    "+",
    ":resize",
    "#(:font :active-color)",
    "send",
    ":state",
    ":flat",
    ":background",
    ":parent",
    "(:button :enterleave)",
    ":active-color",
    ":colormap",
    "get-redish-pixel",
    ":locate-item",
    ":newsize",
    ":raise",
    ":move",
    ":3d-fill-rectangle",
    ":up",
    "event",
    "*buttonrelease-wanted*",
    ":unmap",
    ":width",
    ":draw-label",
    "\"@(#)$Id: Xmenu.l,v 1.1.1.1 2003/11/20 07:46:35 eus Exp $\"",
    "\"X\"",
    "\"X\"",
    "*package*",
    "\"no such package\"",
    ":xdecl",
    "\"Xdecl\"",
    "require",
    "menu-panel",
    "\"(self class &rest args &key (font font-cour12) (border-width 2) (width 100) (color *bisque1*) &allow-other-keys)\"",
    ":find-button",
    "\"(self class label)\"",
    "\"(self class)\"",
    ":create-item",
    "\"(self class klass label receiver method &rest args &key (font fontid) (active-color) &allow-other-keys)\"",
    ":draw-panel",
    "\"(self class)\"",
    ":popup",
    "\"(self class x y &optional (offset 20))\"",
    ":buttonrelease",
    "\"(self class event)\"",
    ":mapnotify",
    "\"(self class event)\"",
  };
