static pointer CLO2062();
static pointer (*ftab[7])();

#define QUOTE_STRINGS_SIZE 89
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "#(:item-height :item-width :font :background :parent :event-mask)",
    "font-lucidasans-bold-12",
    ":background",
    "*bisque1*",
    "send-message",
    "super",
    ":create",
    ":border-width",
    ":parent",
    ":event-mask",
    "font-id",
    ":font",
    ":height",
    ":width",
    ":colormap",
    "get-lighter-pixel",
    "make-topleft-edge-polygon",
    ":flush",
    "event",
    ":redraw",
    ":resize",
    ":associate",
    "max",
    ":move",
    ":y",
    ":map",
    "#(:x :y :font)",
    ":locate-item",
    "send",
    "#(:x :y :font)",
    "menubar-panel",
    ":unmap-menu",
    ":popup-menu",
    ":destroy",
    "send-all",
    ":window-main-loop",
    "#(:font :width :height)",
    "\"x\"",
    "textdots",
    ":3d-fill-rectangle",
    ":x",
    "\"X\"",
    "\"X\"",
    "*package*",
    "\"no such package\"",
    ":xdecl",
    "\"Xdecl.l\"",
    "require",
    "nil",
    "panel",
    "\"(self class &rest args &key ((:item-height iheight) 28) ((:item-width iwidth) 50) (font font-lucidasans-bold-12) ((:background color)) (parent) (event-mask nil) &allow-other-keys)\"",
    ":expose",
    "\"(self class event)\"",
    "\"(self class)\"",
    "\"(self class w h)\"",
    ":items",
    "\"(self class)\"",
    "\"(self class item &optional x y)\"",
    ":create-item",
    "\"(self class klass label receiver method &rest args &key (x) (y) (font fontid) &allow-other-keys)\"",
    ":create-menubar",
    "\"(self class &rest args &key (x 0) (y 0) (font fontid) &allow-other-keys)\"",
    ":active-menu",
    "\"(self class w)\"",
    ":delete-items",
    "\"(self class)\"",
    ":quit",
    "\"(self class &rest a)\"",
    ":keyenter",
    "\"(self class pos)\"",
    ":buttonpress",
    "\"(self class pos)\"",
    ":buttonrelease",
    "\"(self class pos)\"",
    ":motionnotify",
    "\"(self class pos)\"",
    ":enternotify",
    "\"(self class event)\"",
    ":leavenotify",
    "\"(self class pos)\"",
    "\"(self class &rest args &key (font font-lucidasans-bold-12) width height &allow-other-keys)\"",
    "\"(self class item &optional x y)\"",
    ":popup-all-menus",
    "\"(self class)\"",
    ":unmap-all-menus",
    "\"(self class)\"",
    ":xpanel",
    "\"@(#)$Id: Xpanel.l,v 1.1.1.1 2003/11/20 07:46:35 eus Exp $\"",
    "provide",
  };
