static pointer UWP2806();
static pointer (*ftab[21])();

#define QUOTE_STRINGS_SIZE 277
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "#(:width :height :font :rows :columns :event-mask :parent)",
    "(:key :button :enterleave)",
    "*root*",
    "font-id",
    "xwindow",
    ":font",
    "font-courb12",
    "\"X\"",
    "textdots",
    "send-message",
    "super",
    ":create",
    ":width",
    ":height",
    ":event-mask",
    ":parent",
    ":clear-area",
    ":x",
    ":y",
    ":xy",
    ":string",
    "#(:width :height :rows :columns :event-mask :show-cursor :notify-object :notify-method)",
    "(:key :button :enterleave)",
    "make-string",
    ":set-notify",
    ":show-cursor",
    ":clear",
    ":cursor",
    ":on",
    ":off",
    ":toggle",
    ":function",
    ":xorreverse",
    "*display*",
    "fillrectangle",
    ":copy",
    ":goto",
    "copyarea",
    "cleararea",
    ":scroll",
    ":clear-eol",
    ":clear-in-line",
    ":clear-lines",
    "10",
    ":newline",
    "9",
    ":image-string",
    ":advance",
    ":start",
    "position",
    ":putch",
    "event",
    "event-y",
    "event-x",
    ":event-row",
    ":event-col",
    ":resize",
    "/=",
    "setinputfocus",
    ":end2",
    "replace",
    ":insert",
    ":getstring",
    "xflush",
    ":init",
    "textwindowstream",
    ":input",
    ":output",
    "make-two-way-stream",
    "count",
    ":end",
    "fill",
    "(:key :button :motion :enterleave)",
    ":refresh",
    ":fill-pointer",
    "make-array",
    ":refresh-line",
    ":refresh-in-line",
    ":refresh-lines",
    ":reverse",
    ":refresh-area",
    "max",
    "cons",
    "length",
    "open",
    ":max-line-length",
    "string",
    ":initial-contents",
    ":start1",
    ":start2",
    "(8 2)",
    ":goback",
    "127",
    ":delete",
    "12",
    "3",
    ":window-main-loop",
    "(4 11)",
    "6",
    "(10 13)",
    ":highlight",
    ":down",
    ":up",
    ":region-direction",
    "#(:scroll-bar :horizontal-scroll-bar)",
    "xscroll-bar",
    ":gravity",
    ":northeast",
    "xhorizontal-scroll-bar",
    ":southwest",
    ":locate-scroll-bar",
    ":move",
    "(0)",
    "(0)",
    ":move-handle",
    ":line-in-window-p",
    ":foreground",
    ":background",
    ":horizontal-scroll",
    "(10 13)",
    "member",
    ":insert-newline",
    ":insert-char",
    ":buttonpress",
    ":display-selection",
    ":selection",
    "\"@(#)$Id: Xtext.l,v 1.1.1.1 2003/11/20 07:46:36 eus Exp $\"",
    "\"X\"",
    "\"X\"",
    "*package*",
    "\"no such package\"",
    ":xdecl",
    "\"Xdecl.l\"",
    "require",
    "(make-textwindow-stream)",
    "textedit",
    ":global",
    ":super",
    "textwindow",
    ":slots",
    "(total-lines lines)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "characterwindow",
    "\"(self class &rest args &key (width 256) (height 256) (font) rows columns (event-mask '(:key :button :enterleave)) (parent *root*) &allow-other-keys)\"",
    "\"(self class &optional (r 0) (c 0))\"",
    "\"(self class start count)\"",
    ":put-line",
    "\"(self class row col str)\"",
    "\"(self class &rest args &key width height rows columns (event-mask '(:key :button :enterleave)) (show-cursor nil) (notify-object nil) (notify-method nil) &allow-other-keys)\"",
    "\"(self class receiver method)\"",
    "\"(self class flag)\"",
    "\"(self class &optional (switch :toggle))\"",
    ":win-row",
    "\"(self class)\"",
    ":win-col",
    "\"(self class)\"",
    ":win-row-max",
    "\"(self class)\"",
    ":win-col-max",
    "\"(self class)\"",
    "\"(self class &optional (r win-row) (c win-col))\"",
    "\"(self class r c &optional (cursor :on))\"",
    "\"(self class &optional (csr :on))\"",
    "\"(self class &optional (n 1))\"",
    "\"(self class &optional (n 1) &aux srcy desty erasey)\"",
    "\"(self class &optional (n 1) &aux srcx destx erasex)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class &optional (r win-row) (c win-col) (csr :on))\"",
    "\"(self class lines &optional (r win-row))\"",
    ":clear-eos",
    "\"(self class &optional (r win-row) (c win-col))\"",
    "\"(self class row scol ecol)\"",
    ":clear-text-area",
    "\"(self class startrow startcol endrow endcol)\"",
    "\"(self class ch)\"",
    ":putstring",
    "\"(self class str &optional (e (length str)))\"",
    "\"(self class ch)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    ":buttonrelease",
    "\"(self class event)\"",
    "\"(self class w h)\"",
    ":configurenotify",
    "\"(self class event)\"",
    ":echo",
    "\"(self class flag)\"",
    "\"(self class)\"",
    ":enternotify",
    "\"(self class event)\"",
    ":leavenotify",
    "\"(self class event)\"",
    ":keyrelease",
    "\"(self class event)\"",
    ":lineenter",
    "\"(self class line &optional (len (length line)))\"",
    ":keyenter",
    "\"(self class ch &optional event)\"",
    ":fill",
    "\"(self class)\"",
    ":flush",
    "\"(self class)\"",
    "\"(self class xtext direction)\"",
    "make-textwindow-stream",
    "\"(xwin)\"",
    "expand-tab",
    "\"(src &optional (offset 0))\"",
    "buffertextwindow",
    "\"(self class &rest args)\"",
    ":redraw",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class &optional (r win-row) (c win-col))\"",
    "\"(self class &optional (start 0))\"",
    "\"(self class row scol ecol)\"",
    "\"(self class lines srow)\"",
    "\"(self class startrow startcol endrow endcol)\"",
    "\"(self class flag srow scol erow ecol)\"",
    "\"(self class r c &optional (csr :on))\"",
    ":line",
    "\"(self class n)\"",
    ":lines",
    "\"(self class)\"",
    ":nlines",
    "\"(self class)\"",
    ":all-lines",
    "\"(self class)\"",
    "\"(self class)\"",
    ":read-file",
    "\"(self class fname)\"",
    ":display-line-string",
    "\"(self class string)\"",
    ":display-strings",
    "\"(self class strings)\"",
    ":insert-string",
    "\"(self class str &optional (end (length str)))\"",
    "\"(self class ch)\"",
    "\"(self class n)\"",
    "\"(self class ch &optional event)\"",
    "\"(self class event)\"",
    "\"(self class origin current-row current-col)\"",
    ":motionnotify",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class)\"",
    "scrolltextwindow",
    "\"(self class &rest args &key (scroll-bar nil) (horizontal-scroll-bar nil) &allow-other-keys)\"",
    "\"(self class)\"",
    "\"(self class r c &optional (csr :on))\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class &optional (offset 0) (lines (- win-row-max offset)))\"",
    "\"(self class ln)\"",
    "\"(self class ln &optional (highlight nil) &aux fg-save bg-save)\"",
    ":locate",
    "\"(self class n)\"",
    "\"(self class selection)\"",
    "\"(self class)\"",
    ":scroll-fraction",
    "\"(self class)\"",
    ":horizontal-scroll-fraction",
    "\"(self class)\"",
    "\"(self class n)\"",
    "\"(self class n)\"",
    "\"(self class c &optional (refresh t))\"",
    "\"(self class &optional (refresh t))\"",
    "\"(self class thing &optional (refresh t))\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class w h)\"",
    "\"(self class event)\"",
  };
