# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$backslash${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28176" SRC="img25.gif"  > '; 
$key = q/{figure}[h]centertabularccepsfilefile=figmars.eps,scale=0.3;SPMamp;epsfilefile=figsimst.ps,hscale=0.42,vscale=0.45tabularcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure26734" SRC="img103.gif"  > '; 
$key = q/{emtabbing}bf:createit=labelrecievermethod`[method]>&restargs>&key(menunil)(items)(state:flat)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23495" SRC="img80.gif"  > '; 
$key = q/{emtabbing}bf:createitlabelrecievermethod=&restargs`[method]>&key=(choices'(;SPMquot;0;SPMquot;;SPMquot;1;SPMquot;))(initial-choice0)>>(font(sparent:gc:font))>>(button-size13)>>(border-width0)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23617" SRC="img82.gif"  > '; 
$key = q/{figure}centerepsfilefile=figbeam.ps,height=10cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure14964" SRC="img49.gif"  > '; 
$key = q/{figure}[b]centerepsfilefile=figthreadfig.ps,width=130mmlabelthreadmodelcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure12722" SRC="img37.gif"  > '; 
$key = q/{figure}epsfilefile=figeta3colavo.ps,width=150mm{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure374" SRC="img3.gif"  > '; 
$key = q/{_inline}$pi${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tex2html_wrap_inline28121" SRC="img16.gif"  > '; 
$key = q/{_inline}$-2timespi${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28127" SRC="img19.gif"  > '; 
$key = q/{emtabbing}bf:createit&restargs=&key=(items)(border-width0)(fontfont-courb12)`[method]>>(width100)(height-offset15)(color*bisque1*)(active*bisque2*)>&allow-other-keys)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23317" SRC="img75.gif"  > '; 
$key = q/{table}centerlargetabular|lll|hlineand;SPMamp;flet;SPMamp;quoteblock;SPMamp;function;SPMamp;return-fromcatch;SPMamp;go;SPMamp;setqcond;SPMamp;if;SPMamp;tagbodydeclare;SPMamp;labels;SPMamp;thedefmacro;SPMamp;let;SPMamp;throwdefmethod;SPMamp;let*;SPMamp;unwind-protectdefun;SPMamp;progn;SPMamp;whileeval-when;SPMamp;or;SPMamp;hlinetabularcenter{table}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="table578" SRC="img9.gif"  > '; 
$key = q/{table}centertabular|l|r|r|r|r|c|hlineprocessors;SPMamp;1;SPMamp;2;SPMamp;4;SPMamp;8;SPMamp;GC(ratio)hline(a)compiledFibonacci;SPMamp;1.0;SPMamp;2.0;SPMamp;4.0;SPMamp;7.8;SPMamp;0hline(b)interpretedFibonacci;SPMamp;1.0;SPMamp;1.7;SPMamp;2.7;SPMamp;4.4;SPMamp;0hline(c)copy-seq;SPMamp;1.0;SPMamp;1.3;SPMamp;0.76;SPMamp;0.71;SPMamp;0.15hline(d)make-cube;SPMamp;1.0;SPMamp;0.91;SPMamp;0.40;SPMamp;0.39;SPMamp;0.15hline(e)interference-check;SPMamp;1.0;SPMamp;0.88;SPMamp;0.55;SPMamp;0.34;SPMamp;0.21hlinetabularcenter{table}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="table12783" SRC="img41.gif"  > '; 
$key = q/{_inline}$frace^x-e^-x2${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28161" SRC="img20.gif"  > '; 
$key = q/{figure}centerepsfilefile=figsynchports.ps,width=130mmlabelsynchportscenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure12763" SRC="img40.gif"  > '; 
$key = q/{_inline}$2^-21${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tex2html_wrap_inline28117" SRC="img15.gif"  > '; 
$key = q/{figure}[tb]centerepsfilefile=figblock1.edg.ps,height=9cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure24767" SRC="img96.gif"  > '; 
$key = q/{_inline}$times${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28322" SRC="img46.gif"  > '; 
$key = q/{emtabbing}bf:change-attributesit&key=functionplane-maskforegroundbackground`[method]>line-widthline-stylecap-stylejoin-stylefontdashrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing21810" SRC="img68.gif"  > '; 
$key = q/{_inline}$2^2+2+2=2^6=64${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tex2html_wrap_inline28409" SRC="img69.gif"  > '; 
$key = q/{emtabbing}bf:edge1it&optional=(method1)`[method]>(th1*edge-intensity-threshold*)(th2*weak-edge-threshold*)>(run*edge-length-threshold*)(win*color-viewer*)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing25658" SRC="img91.gif"  > '; 
$key = q/{_inline}$sim${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tex2html_wrap_inline28264" SRC="img30.gif"  > '; 
$key = q/{_inline}$pi2${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28125" SRC="img18.gif"  > '; 
$key = q/{_inline}$tcdotpvert+(1-t)nvert${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28373" SRC="img52.gif"  > '; 
$key = q/{emtabbing}bf:initit&key=:poshspace8mm=#f(000)`[method]>:rot>#2f((100)(010)(001))>:rpy>rollpitchyaw>:Euler>azayaz2>:axis>rotation-axis>:angle>rotation-angle>:4X4>4x4matrix>:coords>anothercoordinates>:properties>alistof(ind.value)pair>:name>namepropertyrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing14647" SRC="img47.gif"  > '; 
$key = q/{_inline}$|fltvec-fltvec2|^2${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28314" SRC="img44.gif"  > '; 
$key = q/{figure}[hb]centerepsfilefile=figpointer.pscenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure386" SRC="img5.gif"  > '; 
$key = q/{figure}centertabularccepsfilefile=figrobot-ui2.ps,hscale=0.5,vscale=0.5;SPMamp;epsfilefile=figrobot-st2.ps,scale=0.4tabularcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure26751" SRC="img104.gif"  > '; 
$key = q/{emtabbing}bfdraw-segmentsitsegs&key=(line-gcimage::*red-gc*)(ellipse-gcline-gc)`[function]>(vsgeometry:*viewsurface*)(height(svs:height))(stepnil)>(x0)(y0)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing25876" SRC="img95.gif"  > '; 
$key = q/{emtabbing}bf:createit&key(=(:parent*root*)`[method]>(x0)(y0)(size256)(widthsize)(heightsize)(border-width2)>(save-undernil)(backing-store:always)(backing-pixmapnil)>(border*fg-pixel*)(background*bg-pixel*)>(mapT)(gravity:northwest)>(title;SPMquot;WINDOW;SPMquot;)(nametitle)>(font)>event-mask(:key:button:enterLeave:configure:motion)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing21253" SRC="img66.gif"  > '; 
$key = q/{_inline}$widthtimesheight${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28417" SRC="img90.gif"  > '; 
$key = q/{figure}[h]epsfilefile=figfig-peg-in-hole1.ps,width=7.9cmepsfilefile=figfig-peg-in-hole2.ps,width=7.9cmepsfilefile=figfig-peg-in-hole3.ps,width=7.9cmepsfilefile=figfig-peg-in-hole4.ps,width=7.9cmlabelfig:peg-in-hole{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure17950" SRC="img55.gif"  > '; 
$key = q/{figure}[hbt]centerepsfilefile=figobject.pscenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure398" SRC="img6.gif"  > '; 
$key = q/{_inline}$e^x${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tex2html_wrap_inline28169" SRC="img23.gif"  > '; 
$key = q/{emtabbing}bf:create-itemitklasslabelreceivermethod=&restargs`[method]>&key((fontfontid)>&allow-other-keys)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23162" SRC="img73.gif"  > '; 
$key = q/{_inline}$rowsizetimescolumnsize${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28320" SRC="img45.gif"  > '; 
$key = q/{emtabbing}bfdefclassitclassname&key=:superobject`[macro]>:slots({var_inline$|$_inline(var[:typetype][:forwardselectors])}*)>:metaclassmetaclass>:element-typet>:size-1rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing2083" SRC="img12.gif"  > '; 
$key = q/{emtabbing}bf:createitnamerecievermethod=&restargs`[method]>&key((:widthw)100)((:heighth)100)(fontfont-courb12)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23397" SRC="img78.gif"  > '; 
$key = q/{emtabbing}bf:createit&key=(drawabledefaultRootWindow)`[method]>(foreground*fg-pixel*(background*bg-pixel*)>functionplane-mask>line-widthline-stylecap-stylejoin-style>fontdashrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing21630" SRC="img67.gif"  > '; 
$key = q/{emtabbing}bfopenitpath&key=:direction:input`[function]>:if-exists:new-version>:if-does-not-exist>:permission#o644>:buffer-size512rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing7990" SRC="img29.gif"  > '; 
$key = q/{figure}small<verbatim_mark>verbatim1normalsize{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure418" SRC="img7.gif"  > '; 
$key = q/{emtabbing}bf:createit=&restargs`[method]>&key=((:namenm))((:handh))((:jointsj))((:left-fingerlf))((:right-fingerrf))>>((:toolcoordstc)(make-coords))((:handcoordshc)(make-coords))>>((:basebs)(make-cascoords))(open-direction(floatvector010))>>((:max-spanmspan)100.0)((:leftylft)t)((:acta)nil)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing26712" SRC="img98.gif"  > '; 
$key = q/{emtabbing}bf:edge1it&optional=(method1)`[method]>(th1*edge-intensity-threshold*)(th2*weak-edge-threshold*)>(run*edge-length-threshold*)(wingeometry:*viewsurface*)(edgeimg1)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing25457" SRC="img89.gif"  > '; 
$key = q/{emtabbing}bf:createit&restargs=&key=((:item-heightiheight)30)((:item-widthiwidth)50)`[method]>>(fontfont-lucidasans-bold-12)((:backgroundcolor)*bisque1*)>&allow-other-keys)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23115" SRC="img71.gif"  > '; 
$key = q/{_inline}$2^-21=4.768368times10^-7${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28115" SRC="img14.gif"  > '; 
$key = q/{tabular}llutilities.lpolygonalvoronoi.ltestdata.l;SPMamp;Thisfilecontainsdemonstrationdata,withtheaboveformat{tabular}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tabular18060" SRC="img58.gif"  > '; 
$key = q/{emtabbing}bfviewit&key=(size500)(widthsize)(heightsize)`[function]>(x100)(y100)>(title;SPMquot;eusx;SPMquot;)>(border-width3)>(background0)>(viewpoint#f(300200100))(target#f(000))>(viewdistance5.0)(hither100.0)(yon10000.0)>(screen1.0)(screen-xscreen)(screen-yscreen)>(xcenter500)(ycenter400)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing19372" SRC="img63.gif"  > '; 
$key = q/{table}centerfootnotesizetabular|l|l|hlineFILES;SPMamp;thisdocumentREADME;SPMamp;abriefguidetolisence,installationandsamplerunVERSION;SPMamp;EUSLispversionnumberbin;SPMamp;executables(eus,euscompandeusx)c;SPMamp;EusLispkernelwritteninCl;SPMamp;kernelfunctionswritteninEusLispcomp;SPMamp;EusLispcompilerwritteninEusLispclib;SPMamp;libraryfunctionswritteninCdoc;SPMamp;documentation(latexandjlatexsourcesandmemos)geo;SPMamp;geometricandgraphicprogramslib;SPMamp;sharedlibraries(.so)andstart-upfilesllib;SPMamp;Lisplibraryllib2;SPMamp;secondaryLisplibrarydevelopedatUTYOxwindow;SPMamp;X11interfacemakefile@;SPMamp;symboliclinktooneofmakefile.sun[34]os[34],.vax,etc.pprolog;SPMamp;tinyprologinterpreterxview;SPMamp;xviewtoolkitinterfacetool;SPMamp;vxworks;SPMamp;interfacewithVxWorksreal-timeOSrobot;SPMamp;robotmodelsandsimulatorsvision;SPMamp;imageprocessingprogramscontact;SPMamp;motionconstraintsolverbyH.HirukawaciteHirukawa:1991a,Hirukawa:1991b,Hirukawa:1991cdemo;SPMamp;demonstrativeprogramsbench;SPMamp;benchmarkprogramshlinetabularcenter{table}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="table343" SRC="img2.gif"  > '; 
$key = q/{emtabbing}bfedge2itimg1edge1result&key=(kvalue8.0)`[function]>(curve-threshold0.8)(line-error2.8)>(curve-error2.8)(plane-limit0.3)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing25747" SRC="img93.gif"  > '; 
$key = q/{_inline}$norm((p2-p1)times(p3-p1))${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28331" SRC="img51.gif"  > '; 
$key = q/{figure}centerepsfilefile=figpanelitem.ps,height=5cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure22628" SRC="img85.gif"  > '; 
$key = q/{emtabbing}bf:createitlabelrevcievermethod=&restargs`[method]>&key=widthheight(font(sparent:gc:font))>>(background(sparent:gc:background))>>(border-width0)>>(state:top)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23440" SRC="img79.gif"  > '; 
$key = q/{emtabbing}bf:initit&key=:hitherhspace5mm=100.0`[method]>:yon>1000.0>:aspect>1.0>:screen>100.0>:screen-x>screen>:screen-y>(*screen-xaspect)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing18765" SRC="img62.gif"  > '; 
$key = q/{_inline}$frace^x+e^-xe^x-e^-x${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28165" SRC="img22.gif"  > '; 
$key = q/{figure}centerepsfilefile=figxdraw.ps,height=6cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure19802" SRC="img65.gif"  > '; 
$key = q/{_inline}$frace^x+e^-x2${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28163" SRC="img21.gif"  > '; 
$key = q/{emtabbing}bfsystem:binloaditopathqpath&optional=(entry(pathname-nameopath))`[function]>(symfile;SPMquot;usrlocalbineus;SPMquot;)>(symout;SPMquot;a.out;SPMquot;)>(ldopt;SPMquot;;SPMquot;)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing10001" SRC="img34.gif"  > '; 
$key = q/{emtabbing}bfmake-arrayitdims&key=(element-typevector)`[function]>(initial-contentsnil)>(initial-elementnil)>(fill-pointernil)>(displaced-tonil)>(displaced-index-offset0)>(adjustablenil)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing6756" SRC="img27.gif"  > '; 
$key = q/{emtabbing}bfloaditfname&key=:verbosehspace20mm=*load-verbose*>:package>*package*>:entry>(pathname-namefname)>:symbol-input>;SPMquot;usrlocalbineus;SPMquot;>:symbol-output>;SPMquot;a.out;SPMquot;>:ld-option>;SPMquot;;SPMquot;rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing9908" SRC="img33.gif"  > '; 
$key = q/{figure}[h]centerepsfilefile=figfig-peg-naname-m1.ps,width=7.9cmepsfilefile=figfig-peg-naname-m2.ps,width=7.9cmepsfilefile=figfig-peg-naname-m3.ps,width=7.9cmepsfilefile=figfig-peg-naname-m4.ps,width=7.9cmcenterlabelfig:peg-in-a-hole{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure17958" SRC="img56.gif"  > '; 
$key = q/{figure}centertabularccepsfilefile=figthreadobj.ps,width=7.5cm;SPMamp;epsfilefile=figthreadpool.ps,width=7.5cmtabularcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure12745" SRC="img39.gif"  > '; 
$key = q/{tabular}llutilities.l;SPMamp;Geometricutilityfunctions,plusEUSXgraphicfunctionspolygonalvoronoi.l;SPMamp;Theprogram.testdata.l;SPMamp;Demonstrationdata,withtheaboveformat.{tabular}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tabular18057" SRC="img57.gif"  > '; 
$key = q/{emtabbing}bf:createitlabelrevcievermethod=&restargs`[method]>&key(fontfont-courb12)(columns20)(initial-value)(border-width0)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23809" SRC="img86.gif"  > '; 
$key = q/{figure}centerepsfilefile=figfilepanel.ps,height=7.5cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure22467" SRC="img76.gif"  > '; 
$key = q/{_inline}$2timespi${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28123" SRC="img17.gif"  > '; 
$key = q/{_inline}$|fltvec|^2=(bfv.fltvecfltvec)${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28310" SRC="img43.gif"  > '; 
$key = q/{_inline}$atan(normalcdot(v1timesv2),v1cdotv2)${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28325" SRC="img50.gif"  > '; 
$key = q/{figure}centerepsfilefile=figfig1.ps,height=19cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure15599" SRC="img54.gif"  > '; 
$key = q/{emtabbing}bf:createitbitmap-filerecievermethod=&restargs`[method]>&keywidthheight>&allow-other-keys)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23561" SRC="img81.gif"  > '; 
$key = q/{emtabbing}bf:create-menubarit=&restargs`[method]>&key(fontfontid)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23192" SRC="img74.gif"  > '; 
$key = q/{figure}centerepsfilefile=figeta3coords.ps,height=100mmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure26393" SRC="img100.gif"  > '; 
$key = q/{emtabbing}bfedge1itimg=&optional=(method1)`[function]>>(th1*edge-intensity-threshold*)(th2*weak-edge-threshold*)>>(run*edge-length-threshold*)result>&aux(width(simg:width))(height(simg:height))rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing25710" SRC="img92.gif"  > '; 
$key = q/{emtabbing}bf:createitlabelrecievermethod=&restargs`[method]>&key(min0.0)(max1.0)(parent)>(min-label;SPMquot;;SPMquot;)(max-label;SPMquot;;SPMquot;)(value-format;SPMquot;~4,2f;SPMquot;)>(fontfont-courb12)(span100)(border-width0)(initial-valuemin)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23704" SRC="img83.gif"  > '; 
$key = q/{emtabbing}bfdraw-ellipse-segmentitelpgc&optional=(vs*viewsurface*)(height(svs:height))`[function]>(x0)(y0)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing25849" SRC="img94.gif"  > '; 
$key = q/{_inline}$arrayllT;SPMamp;=basecdotJ1cdotJ2cdotldotscdotJ6cdothandcoordscdottoolcoords;SPMamp;=(s;eta3;:worldcoords)T_Jn;SPMamp;=basecdotJ1cdotldotscdotJn;SPMamp;=(s;Jn;:worldcoords)T_arm;SPMamp;=J1cdotJ2cdotldotscdotJ6cdothandcoords;SPMamp;=(s;eta3;:armsol-coords)T_tool;SPMamp;=J1cdotJ2cdotldotscdotJ6cdothandcoordscdottoolcoords;SPMamp;=(s;eta3;:copy-coords)T_t;SPMamp;=toolcoords;SPMamp;=(manipulator-toolcoords;eta3)T_t^-1;SPMamp;=toolcoords^-1;SPMamp;=(manipulator-toolinverse;eta3)T_h;SPMamp;=handcoords;SPMamp;=(manipulator-handcoords;eta3)array${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28426" SRC="img99.gif"  > '; 
$key = q/{emtabbing}bfcompile-fileitsrcfile&key=(:verbosenil)hspace43mm=`[function]>(:optimize2)(:c-optimize1)(:safety1)>rm;optimizationlevel>(:pict)>rm;generatepositionindep->>rmentcodetobuildlibrary>(:cct)>rm;runccompiler>(:entry(pathname-namefile))rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing9833" SRC="img32.gif"  > '; 
$key = q/{figure}centerepsfilefile=figparathreads.ps,width=120mmlabelparathreadscenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure12734" SRC="img38.gif"  > '; 
$key = q/{figure}centerepsfilefile=figpanellayout.ps,height=7cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure22379" SRC="img72.gif"  > '; 
$key = q/{figure}centerepsfilefile=figviewcoords.ps,height=10cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure18081" SRC="img60.gif"  > '; 
$key = q/{_inline}$parametercdotpvert+(1-parameter)nvert${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=MIDDLE ALT="tex2html_wrap_inline28375" SRC="img53.gif"  > '; 
$key = q/{figure}centerepsfilefile=figtextviewpanel.ps,height=7cmcenter{figure}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="figure22477" SRC="img77.gif"  > '; 
$key = q/{emtabbing}bf:createit=&restargs`[method]>&key=widthheight(fontfont-courb14)rowscolumns>(show-cursornil)(notify-objectnil)(notify-methodnil)>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23882" SRC="img87.gif"  > '; 
$key = q/{emtabbing}bf:createitnamerecievermethod=&restargs`[method]>&key=(stick-size5)(returnnil)>>(min-x-1.0)(max-x1.0)>>(min-y-1.0)(max-y1.0)>&allow-other-keys)rm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing23754" SRC="img84.gif"  > '; 
$key = q/{_inline}$rightarrow${_inline}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="tex2html_wrap_inline28431" SRC="img102.gif"  > '; 
$key = q/{emtabbing}bf:initit&key=:targethspace12mm=#f(000)`[method]>:view-direction>nil>:view-up>#f(0.00.01.0))>:view-right>nil>&allow-other-keysrm{emtabbing}/;
$cached_env_img{$key} = ' <IMG  ALIGN=BOTTOM ALT="emtabbing18629" SRC="img61.gif"  > '; 

1;

