static pointer UWP88();
static pointer UWP90();
static pointer UWP178();
static pointer UWP186();
static pointer (*ftab[8])();

#define QUOTE_STRINGS_SIZE 91
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":element-type",
    ":byte",
    "make-array",
    "open",
    ":infd",
    ":outfd",
    "(32 9 10)",
    "member",
    "\"undefined read-ascii-pbm\"",
    "\"undefined read-binary-pbm\"",
    ":width",
    ":height",
    "\"P5 ~d ~d ~d~%\"",
    "\"unexpected EOF\"",
    "grayscale-image",
    ":init",
    ":name",
    ":fname",
    "pathname-name",
    "make-string",
    ":instream",
    ":tail-string",
    "replace",
    ":discard",
    "\"EOF hit while reading pgm file\"",
    "color-image24",
    "\"unexpected EOF\"",
    "\"unexpected EOF\"",
    "\"unexpected EOF\"",
    ":to24",
    "\"P6 ~d ~d ~d~%\"",
    ":entity",
    "\"not a p[bgp]m file\"",
    "\"image too big or negative\"",
    "(49 52)",
    "(50 53)",
    "(51 54)",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "\"unknown pbm magic number\"",
    "color-image",
    "multi-channel-image",
    ":direction",
    ":output",
    "\"IMAGE\"",
    "\"IMAGE\"",
    ":nicknames",
    "(\"IMG\" \"IP\")",
    "make-package",
    "\"IMAGE\"",
    "\"IMAGE\"",
    "*package*",
    "\"no such package\"",
    "(read-pnm-file read-pnm write-pgm write-ppm write-pnm write-pnm-file)",
    "read-raw-image",
    "\"read a file of raw pixel data\"",
    "write-raw-image",
    "\"write pixel data out to a file\"",
    "read-pbm-token",
    "\"(f eof)\"",
    "read-ascii-pbm",
    "\"(f img width height)\"",
    "read-binary-pbm",
    "\"(f img width height)\"",
    "write-pgm",
    "\"write-pgm always uses binary format\"",
    "read-ascii-pgm",
    "\"(f img width height)\"",
    "read-binary-pgm",
    "\"(f img width height)\"",
    "read-binary-ppm",
    "\"(f rgb width height)\"",
    "read-ascii-ppm",
    "\"(f rgb width height)\"",
    "write-ppm",
    "\"write-ppm always uses binary (P6) format\"",
    "read-pnm",
    "\"(f &optional buf0)\"",
    "read-pnm-file",
    "\"(file &optional buf)\"",
    "write-pnm",
    "\"(f img)\"",
    "write-pnm-file",
    "\"(file img)\"",
    ":pbmfile",
    "\"#(@)$Id: pbmfile.l,v 1.1.1.1 2003/11/20 07:46:30 eus Exp $\"",
    "provide",
  };
