static pointer (*ftab[4])();

#define QUOTE_STRINGS_SIZE 44
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "super",
    ":init",
    ":update-x-major",
    ":update-y-major",
    "line-dda",
    ":next",
    "expt",
    "/=",
    "*viewsurface*",
    "ellipse-dda",
    "dda",
    ":point",
    ":flush",
    "(dda line-dda ellipse-dda circle-dda draw-ellipse ellipse-dda dda-line)",
    ":global",
    ":super",
    "propertied-object",
    ":slots",
    "((count :integer))",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "((x :integer) (y :integer) (dx :integer) (dy :integer) (err :integer) (errinc :integer) (errdec :integer) (xyinc :integer) (length :integer) (update-method))",
    "(finished xcenter ycenter (a :float) (b :float) (m :float) (eps :float) (ix :integer) (iy :integer) (x :float) (y :float) (ix1 :integer) (iy1 :integer) (x1 :float) (y1 :float))",
    "circle-dda",
    "nil",
    "\"(self class)\"",
    "\"(self class x0 y0 x1 y1)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "dda-line",
    "\"(x0 y0 x1 y1)\"",
    "\"(self class param-a param-b &optional (x-center 0) (y-center 0))\"",
    "\"(self class)\"",
    "dda-ellipse",
    "\"(a b)\"",
    "draw-ellipse",
    "\"(xc yc a b &optional (win *viewsurface*))\"",
    ":dda",
    "\"@(#)$Id: dda.l,v 1.1.1.1 2003/11/20 07:46:28 eus Exp $\"",
    "provide",
  };
