static pointer CLO3239();
static pointer CLO3304();
static pointer (*ftab[11])();

#define QUOTE_STRINGS_SIZE 126
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "*epsilon*",
    "*visible-face-images*",
    ":possibly-hiding",
    ":intersect-line",
    ":color",
    "line-intersection",
    ":point",
    ":homo2real",
    ":add-segment",
    "<=",
    "car",
    "bounding-box",
    ":init2",
    ":projected-point",
    "*visible-faces*",
    ":projected-homo-point",
    "homo-viewport-clip",
    ":collect-segments",
    ":viewpoint",
    ":view",
    "homo2normal",
    ":contourp",
    "#(:edge3 :homo-pvert :homo-nvert :pvert2 :nvert2)",
    ":inner",
    ":intersection-p",
    ":vertices",
    "flatten",
    ":init",
    ":grow",
    "face-image",
    ":edges",
    "gethash",
    ":projected-intersection",
    "*ignore-approximated-edges*",
    ":approximated-p",
    ":size",
    ":hash",
    "system:address",
    ":test",
    "eq",
    "make-hash-table",
    "*visible-edges*",
    "*invisible-edges*",
    "*invisible-faces*",
    "*contour-edge-images*",
    "*non-contour-edge-images*",
    "*projected-edges*",
    "faceset",
    ":worldcoords",
    ":faces",
    ":plane-distance",
    "append",
    ":all-edges",
    "send-all",
    "remove-duplicates",
    "set-difference",
    "edge-image",
    ":project",
    "sethash",
    ":pvert2",
    "#f(-0.9999 -0.9999 0.99)",
    ":nvert2",
    "#f(-0.9999 0.9999 0.99)",
    "#f(-0.9999 0.9999 0.99)",
    "#f(0.9999 0.9999 0.99)",
    "#f(0.9999 0.9999 0.99)",
    "#f(0.9999 -0.9999 0.99)",
    "#f(0.9999 -0.9999 0.99)",
    "#f(-0.9999 -0.9999 0.99)",
    "*hid*",
    ":sort-segments",
    ":mark-visible-segments",
    "\"GEOMETRY\"",
    "\"GEOMETRY\"",
    "*package*",
    "\"no such package\"",
    "(*visible-faces* *visible-face-images* *visible-edges* *contour-edge-images* *hid* *projected-edges* *non-contour-edge-images* *invisible-edges* *invisible-faces* check-visibility *ignore-approximated-edges* hid2)",
    ":vtype",
    ":global",
    ":special",
    "check-visibility",
    "\"args= pface nface  point3d point2d viewpoint\ndetermines visibility of point3d.\"",
    ":edge3",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class p)\"",
    "\"(self class p &optional info)\"",
    "\"(self class p)\"",
    "\"(self class p)\"",
    ":intersecting-point",
    "\"(self class ex)\"",
    "\"(self class ex mutual)\"",
    "\"(self class)\"",
    ":box",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class viewpoint)\"",
    ":visible-face",
    "\"(self class viewpoint)\"",
    "\"(self class flag)\"",
    ":visible-segments",
    "\"(self class)\"",
    ":invisible-segments",
    "\"(self class)\"",
    "\"(self class edge3d view &optional (viewpoint (send view :viewpoint)))\"",
    "\"(self class &key ((:edge3 e)) ((:homo-pvert hp)) ((:homo-nvert hn)) ((:pvert2 p2)) ((:nvert2 n2)))\"",
    ":face3d",
    "\"(self class)\"",
    "\"(self class point)\"",
    ":boxtest",
    "\"(self class b)\"",
    "\"(self class f3d elist viewpoint)\"",
    "make-face-image",
    "\"(f edge-images-htab viewpoint)\"",
    "set-contour-intersections",
    "\"(contour-images)\"",
    "set-non-contour-intersections",
    "\"(non-contour-images contour-images)\"",
    "curved-edge-image-p",
    "\"(eimg)\"",
    "hid2",
    "\"(bodies view &optional (vp))\"",
    ":hid",
    "\"@(#)$Id: hid.l,v 1.1.1.1 2003/11/20 07:46:28 eus Exp $\"",
    "provide",
  };
