static pointer CLO3094();
static pointer (*ftab[9])();

#define QUOTE_STRINGS_SIZE 89
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":edges",
    "bounding-box",
    ":box",
    ":intersection-p",
    ":init",
    "*contact-threshold*",
    "homogenize",
    "triangle",
    "super",
    ":dimension",
    "copy-seq",
    "make-bounding-box",
    "make-line",
    ":set-convexp",
    "line-intersection",
    ":on-line-point",
    ":on-edge",
    ":border",
    ":intersect-line",
    "evenp",
    ":boxtest",
    ":lines",
    "eps-in-range",
    ":insidep",
    ":vertices",
    "min",
    ":distance",
    "send-all",
    ":distance-point",
    ":inside",
    "polygon",
    ":draw-arc",
    ":worldpos",
    "send-message",
    "polygon2d",
    "send",
    "circle2d",
    ":foreground",
    ":draw-polygon",
    ":fill-polygon",
    "(polygon2d make-rectangle make-polygon2d fill-polygon2d)",
    ":global",
    ":super",
    "cascaded-coords",
    ":slots",
    "(model-vertices vertices lines convexp box)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    ":drawners",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class b)\"",
    ":update",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class vlist)\"",
    "\"(self class p1 &optional p2)\"",
    "\"(self class p &optional (tolerance *contact-threshold*) &aux res)\"",
    "\"(self class point)\"",
    ":intersect-polygon2d",
    "\"(self class pg)\"",
    "\"(self class pnt)\"",
    "\"(self class pnt)\"",
    ":3d",
    "\"(self class &optional (z 0.0) (klass polygon))\"",
    "(radius)",
    ":radius",
    "\"(self class)\"",
    ":draw",
    "\"(self class v)\"",
    "\"(self class r &rest args)\"",
    "make-polygon2d",
    "\"(&rest vertices)\"",
    "make-rectangle",
    "\"(xsize ysize)\"",
    "make-circle",
    "\"(rad &rest args)\"",
    "\"(self class xwin &optional color)\"",
    ":draw-fill",
    "\"(self class xwin &optional color)\"",
    ":polygon",
    "\"@(#)$Id: polygon.l,v 1.1.1.1 2003/11/20 07:46:28 eus Exp $\"",
    "provide",
  };
