static pointer CLO4319();
static pointer CLO4331();
static pointer CLO4410();
static pointer CLO4436();
static pointer CLO4448();
static pointer (*ftab[15])();

#define QUOTE_STRINGS_SIZE 89
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "\"COMBI\"",
    "let",
    "while",
    "rest",
    "pop",
    "dolist",
    ":all-edges",
    ":colinear-line",
    ":colinear-line-intersection",
    "edge",
    ":init",
    ":pvertex",
    ":nvertex",
    ":faces",
    "eps<",
    "values",
    "polygon",
    ":vertices",
    "face",
    ":edges",
    "hole",
    "projection",
    ":normal",
    ":project",
    ":holes",
    ">=",
    "*f1*",
    "*f2*",
    "face+",
    "member-if",
    "\"line?: \"",
    "break",
    "collect-instances",
    "\"project-shadow: can't find intersection of loops~%\"",
    ":area",
    "line",
    "member",
    "last",
    "line-intersection3",
    ":point",
    "\"loop intermingled\"",
    ":count",
    "delete",
    "assoc",
    "find-if",
    "loops",
    "every",
    ":enter-hole",
    ":face",
    "shadow",
    "\"line?: \"",
    "\"project-shadow: can't find intersection of loops~%\"",
    ":insidep",
    ":inside",
    "face*",
    ":box",
    ":one-inner-point",
    "\"GEO\"",
    "\"GEO\"",
    "*package*",
    "\"no such package\"",
    "(do-combination project-shadow project-shadow1 shadow-intersection closest-shadow)",
    "do-combination",
    "\"(combi &rest forms)\"",
    "polygon-in-contact-p",
    "\"(poly1 poly2)\"",
    "make-edges-from-vertices",
    "\"(verts &aux lines)\"",
    "orthogonally-visible-faces",
    "\"(abody vnormal &aux vfaces ifaces)\"",
    "make-polygon",
    "\"(&rest points)\"",
    "make-face-from-edge-loop",
    "\"(edges)\"",
    "change-to-hole",
    "\"(aface)\"",
    "project-shadow1",
    "\"(bod pln)\"",
    "remove-inner-loop",
    "\"(edge-loop vnormal)\"",
    "project-shadow",
    "\"(bod pln)\"",
    "shadow-intersection",
    "\"(body1 body2 pln)\"",
    "closest-shadow",
    "\"(abody shadow)\"",
    ":shadow",
    "\"@(#)$Id: shadow.l,v 1.1.1.1 2003/11/20 07:46:29 eus Exp $\"",
    "provide",
  };
